version: '3'
services:
  application:
    build: .
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8501:8501
    environment:
      NEO4J_HOST: database 
  database:
    image: neo4j:latest
    healthcheck:
      test: ["CMD", "cypher-shell", "match (n) return count(n)"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 40s
    environment:
      - NEO4J_AUTH=neo4j/1234
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT= "yes"
      - NEO4J_dbms_connector_bolt_enabled= true
      - NEO4J_dbms_security_auth__enabled= false
      - NEO4J_server_bolt_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
      
    ports:
      - 7687:7687
    


   



